# -*- coding: utf-8 -*-
"""Lean proof emission + verification backend.

Two responsibilities:

1. :func:`emit_hypothesis_proof` / :func:`emit_discovery_proof` — generate
   a ``.lean`` proof stub from a record. The stub declares the canonical
   theorem (``theorem_name``), brings the relevant Brian Lean library
   into scope, encodes the obligation as a ``Prop``, and ends in
   ``sorry`` until the human or a Lean tactic discharges it.

2. :func:`verify_lean_proof` — shell out to ``lean --json <file>`` (if a
   ``lean`` binary is on PATH) and return a structured
   :class:`LeanVerdict`. Without the binary the function returns
   ``LeanVerdict(status="skipped")`` so callers can keep moving — the
   record's ``proof_status`` stays at ``"stub"`` until verification
   succeeds elsewhere.

The Lean library namespace is ``Brian.*``; each hypothesis or discovery
gets a unique theorem name like ``Brian.PhiMonotone`` (hypothesis) or
``Brian.Discoveries.D001_NoRegression``. The emitter does *not* try to
write the actual mathematical proof; it lays out the obligation in a
form a Lean tactician (or, later, an automated tactic) can attack.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Union

from neuroslm.discoveries.records import (
    HypothesisRecord, DiscoveryRecord,
)


# ── verdict ────────────────────────────────────────────────────────


@dataclass
class LeanVerdict:
    """Outcome of a single :func:`verify_lean_proof` call.

    Status semantics:
      ``verified``  — Lean accepted the file with 0 errors AND no
                      ``sorry`` remains
      ``compiles``  — Lean accepted the file with 0 errors BUT one or
                      more ``sorry`` remain — kernel didn't reject
                      anything but the obligations are still open
      ``error``     — Lean (or the static lint) reported one or more
                      errors
      ``skipped``   — Lean binary not on PATH (or refused to run)
                      AND the static lint passed
    """
    status: str
    file: str = ""
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    n_sorry: int = 0
    #: True when :func:`static_lint_lean_proof` reported zero
    #: violations. This lets a worker without the Lean toolchain
    #: still record a meaningful intermediate ``proof_status`` —
    #: lint-clean is the strongest claim CI without Lean can make.
    lint_clean: bool = False

    def proof_status_for_record(self) -> str:
        """Map the Lean verdict back to the record's
        :data:`PROOF_STATUSES` vocabulary.

        ``skipped`` + ``lint_clean=True`` is mapped to ``"compiles"``
        rather than ``"stub"``: the file has no banned tokens
        (``sorry`` / ``admit`` / ``Unimplemented``), so it is at
        least structurally sound; the Lean kernel just hasn't had
        the chance to confirm full verification. Once a worker
        with ``lean`` on PATH re-runs ``hypothesis verify`` the
        status is upgraded to ``"verified"``.
        """
        if self.status == "verified":
            return "verified"
        if self.status == "compiles":
            return "compiles"
        if self.status == "skipped" and self.lint_clean:
            return "compiles"
        # Anything else (error, skipped + lint dirty) → stub.
        return "stub"


# ── emission helpers ───────────────────────────────────────────────


def _lean_header_block() -> str:
    """Common imports + module preamble for every Brian Lean file.

    Per CLAUDE.md §12 the only sanctioned import surface for hypothesis
    proofs is `Brian.Core` (or a narrower `Brian.Thsd.*` submodule).
    The autogen template imports `Brian.Core` and uses the
    `Brian.Postulate.Unimplemented "H..."` obligation marker instead
    of `sorry` — the marker compiles in Lean but is caught by
    :func:`static_lint_lean_proof` so any committed file containing
    it fails verification.
    """
    return (
        "/-\n"
        "  Brian — autogenerated Lean proof scaffold.\n"
        "\n"
        "  THIS IS A SCAFFOLD, NOT A COMMIT-READY PROOF.\n"
        "  Per CLAUDE.md §12 the committed state of this file must:\n"
        "    * import Brian.Core (or a narrower Brian.* submodule),\n"
        "    * state its obligation in THSD vocabulary,\n"
        "    * close every theorem with a real proof (no `Unimplemented`).\n"
        "\n"
        "  Replace the `Unimplemented` obligation below with the real\n"
        "  theorem statement and proof body. See hypothesis/proofs/\n"
        "  H001_*.lean for a worked example.\n"
        "-/\n"
        "import Brian.Core\n"
        "\n"
    )


# ── stub markers (used by both the emitter and the linter) ────────


#: Token the autogen scaffold inserts in place of `sorry`. The
#: Python-side static lint (:func:`static_lint_lean_proof`) catches
#: this token in any committed file and returns ``status="stub"``.
UNIMPLEMENTED_MARKER = "Brian.Postulate.Unimplemented"


def _unimplemented_obligation(tag: str) -> str:
    """Lean expression closing a scaffold theorem with the Unimplemented
    marker. Compiles cleanly (Unimplemented := Unit) but is flagged by
    :func:`static_lint_lean_proof`."""
    safe = tag.replace('"', "'")
    return (
        f"{UNIMPLEMENTED_MARKER} \"{safe}\" :=\n"
        f"  Brian.Postulate.unimplemented \"{safe}\""
    )


def _format_metric_block(label: str, metrics: Dict[str, float]) -> str:
    """Render a fitness dict as a Lean comment block — kept verbatim
    in the proof so the kernel can be pointed at the empirical premise
    even before the Brian library models it as a structure."""
    lines = [f"  {label}:"]
    for k in sorted(metrics):
        lines.append(f"    {k} := {metrics[k]}")
    return "\n".join(lines)


def _emit_proof_text(*,
                     record_id: str,
                     theorem_name: str,
                     headline_md: str,
                     obligation_lean: str,
                     extra_comments: Optional[str] = None) -> str:
    """Assemble the final Lean file contents from common parts."""
    sections: List[str] = [_lean_header_block()]
    sections.append(
        f"/-\n  Record: {record_id}\n"
        f"  Obligation (Markdown):\n"
        f"{_indent_md(headline_md, 4)}\n"
        f"-/\n"
    )
    if extra_comments:
        sections.append(f"/-\n{_indent_md(extra_comments, 2)}\n-/\n")
    # `noncomputable` so we can use real-valued definitions without
    # demanding computability proofs.
    sections.append(
        f"noncomputable section\n\n"
        f"namespace {_namespace_of(theorem_name)}\n\n"
        f"-- Autogen scaffold obligation: the `Unimplemented` marker is\n"
        f"-- caught by static_lint_lean_proof. Replace the type and body\n"
        f"-- with the real theorem in THSD vocabulary (CLAUDE.md §12).\n"
        f"{obligation_lean}\n\n"
        f"end {_namespace_of(theorem_name)}\n\n"
        f"end\n"
    )
    return "".join(sections)


def _namespace_of(theorem_name: str) -> str:
    """``Brian.PhiMonotone`` → ``Brian``; ``Brian.Discoveries.D001_X`` →
    ``Brian.Discoveries``."""
    parts = theorem_name.split(".")
    if len(parts) < 2:
        return "Brian"
    return ".".join(parts[:-1])


def _theorem_leaf(theorem_name: str) -> str:
    """The unqualified theorem name — last dotted component."""
    return theorem_name.rsplit(".", 1)[-1]


def _indent_md(text: str, n: int) -> str:
    pad = " " * n
    return "\n".join(pad + line for line in (text or "").splitlines())


# ── public: emit from a hypothesis ─────────────────────────────────


def emit_hypothesis_proof(record: HypothesisRecord,
                          root: Union[str, Path]) -> str:
    """Emit a Lean proof scaffold for ``record`` under ``<root>/proofs/``.

    Args:
        record: the hypothesis record (will be mutated:
                ``proof_path`` is set; ``proof_status`` is set to
                ``"stub"`` only when a fresh scaffold is written).
        root:   the hypothesis directory (the function will create
                ``proofs/`` if it doesn't exist).

    Returns:
        Absolute path to the ``.lean`` file.

    Idempotency contract (CLAUDE.md §12):
        If the target ``.lean`` file already exists AND does NOT
        contain the :data:`UNIMPLEMENTED_MARKER`, the file is left
        untouched — that is a hand-edited proof and clobbering it
        would destroy work. The record's ``proof_path`` is still
        updated to point at the file, but ``proof_status`` is not
        changed (the caller should run :func:`verify_lean_proof`
        afterwards to get a fresh status).
    """
    root = Path(root)
    proofs_dir = root / "proofs"
    proofs_dir.mkdir(parents=True, exist_ok=True)
    out_path = proofs_dir / record.proof_filename()

    # Idempotency: don't clobber a hand-edited proof.
    if out_path.is_file():
        existing = out_path.read_text(encoding="utf-8")
        if UNIMPLEMENTED_MARKER not in existing and "sorry" not in existing:
            # Hand-edited — keep it. Just thread the path back into the
            # record so the ledger stays consistent.
            record.proof_path = _posix_relative(out_path, root.parent)
            return str(out_path.resolve())

    leaf = _theorem_leaf(record.theorem_name)
    obligation = (
        f"theorem {leaf} : "
        + _unimplemented_obligation(f"{record.id} {record.theorem_name}")
    )

    text = _emit_proof_text(
        record_id=record.id,
        theorem_name=record.theorem_name,
        headline_md=record.statement_md,
        obligation_lean=obligation,
        extra_comments=(
            f"References:\n"
            + "\n".join(f"  - {r}" for r in (record.references or [])) + "\n"
            + "Code refs:\n"
            + "\n".join(f"  - {c}" for c in (record.code_refs or [])) + "\n"
            + "Test refs:\n"
            + "\n".join(f"  - {t}" for t in (record.test_refs or []))
        ) if (record.references or record.code_refs or record.test_refs)
            else None,
    )
    out_path.write_text(text, encoding="utf-8")

    # ``proof_path`` is stored as a POSIX-style relative path so the
    # value round-trips identically on Windows, Linux, and macOS — the
    # field lives in checked-in YAML front-matter and needs to be
    # filesystem-portable.
    record.proof_path = _posix_relative(out_path, root.parent)
    record.proof_status = "stub"
    return str(out_path.resolve())


def _posix_relative(target: Path, base: Path) -> str:
    """``target`` expressed relative to ``base``, with ``/`` separators."""
    try:
        return target.resolve().relative_to(base.resolve()).as_posix()
    except ValueError:
        # ``target`` is not under ``base`` — fall back to the absolute
        # POSIX form so the field stays parseable.
        return target.resolve().as_posix()


# ── public: emit from a discovery ──────────────────────────────────


def emit_discovery_proof(record: DiscoveryRecord,
                         root: Union[str, Path]) -> str:
    """Emit a Lean proof scaffold for an autodiscovered mutation.

    The obligation we encode is *"this mutation does not regress any
    fitness coordinate the gates care about"* — a no-regression
    monotonicity claim. The scaffold uses the
    :data:`UNIMPLEMENTED_MARKER` (CLAUDE.md §12); the metric values
    are kept in a comment so the human (or a later tactic) has the
    empirical premise to hand when discharging the obligation.

    Idempotency: like :func:`emit_hypothesis_proof`, an existing
    hand-edited file is preserved.
    """
    root = Path(root)
    proofs_dir = root / "proofs"
    proofs_dir.mkdir(parents=True, exist_ok=True)
    out_path = proofs_dir / record.proof_filename()

    if out_path.is_file():
        existing = out_path.read_text(encoding="utf-8")
        if UNIMPLEMENTED_MARKER not in existing and "sorry" not in existing:
            record.proof_path = _posix_relative(out_path, root.parent)
            return str(out_path.resolve())

    leaf = _theorem_leaf(record.theorem_name)

    # Record the empirical metrics in a Lean comment block so the
    # human reading the scaffold has the raw before/after/delta to
    # hand when writing the real proof. The obligation itself uses
    # the Unimplemented marker (CLAUDE.md §12).
    metric_block = (
        f"/-\n"
        f"  Empirical witness (raw values):\n"
        f"{_format_metric_block('  before', record.fitness_before)}\n"
        f"{_format_metric_block('  after',  record.fitness_after)}\n"
        f"{_format_metric_block('  delta',  record.fitness_delta)}\n"
        f"  Parent genome: {record.parent_dna_id}\n"
        f"  Mutation chain: {', '.join(record.mutation_chain)}\n"
        f"-/\n"
    )
    obligation = (
        metric_block
        + f"theorem {leaf} : "
        + _unimplemented_obligation(f"{record.id} {record.theorem_name}")
    )

    headline = (
        record.mechanism_md.strip()
        + "\n\nObservation: " + ", ".join(
            f"{k}: {record.fitness_before.get(k, 0.0):.3f} -> "
            f"{record.fitness_after.get(k, 0.0):.3f}"
            for k in sorted(set(record.fitness_before) | set(record.fitness_after))
        )
    )
    text = _emit_proof_text(
        record_id=record.id,
        theorem_name=record.theorem_name,
        headline_md=headline,
        obligation_lean=obligation,
        extra_comments=(
            f"Generation: {record.generation}\n"
            f"Mutation chain: {', '.join(record.mutation_chain)}"
        ),
    )
    out_path.write_text(text, encoding="utf-8")
    record.proof_path = _posix_relative(out_path, root.parent)
    record.proof_status = "stub"
    return str(out_path.resolve())


# ── public: verify ─────────────────────────────────────────────────


def _lean_binary() -> Optional[str]:
    """Return the path to the ``lean`` binary, or ``None`` if absent.

    Indirected so tests can monkeypatch it to simulate a no-Lean worker.
    """
    return shutil.which("lean")


def _lake_binary() -> Optional[str]:
    """Return the path to the ``lake`` binary, or ``None`` if absent.

    Lake is preferred over plain ``lean`` because it resolves the
    Brian library's ``LEAN_PATH`` automatically — `import Brian.Core`
    works under ``lake env lean`` but not under bare ``lean``.
    """
    return shutil.which("lake")


def _brian_lean_root() -> Path:
    """Path to the Brian Lean library root (``<repo>/lean``)."""
    return Path(__file__).resolve().parents[2] / "lean"


# ── stub patterns the static linter forbids ───────────────────────


#: Compiled patterns matching tokens that must NOT appear in any
#: committed ``.lean`` file. Each entry is ``(name, regex, message)``.
#:
#: ``sorry`` and ``admit`` are matched only in proof-tactic position
#: (``:= sorry``, ``by sorry``, ``; sorry``, and the variants for
#: ``admit``) — not as identifiers. This means a regular method called
#: ``foo.admit`` does NOT trigger the lint, but a literal proof
#: obligation closed with ``sorry`` does. The
#: ``Brian.Postulate.Unimplemented`` marker is forbidden anywhere
#: because it has no legitimate non-stub use.
_STATIC_LINT_PATTERNS = (
    ("sorry",
     re.compile(r"(?:(?::=)|(?:\bby))\s*sorry\b|;\s*sorry\b|^\s*sorry\b",
                re.MULTILINE),
     "`sorry` is banned in committed .lean proof bodies (CLAUDE.md §12.2)."),
    ("admit",
     re.compile(r"(?:(?::=)|(?:\bby))\s*admit\b|;\s*admit\b|^\s*admit\b",
                re.MULTILINE),
     "`admit` is banned in committed .lean proof bodies (CLAUDE.md §12.2)."),
    ("unimplemented",
     re.compile(re.escape(UNIMPLEMENTED_MARKER)),
     f"`{UNIMPLEMENTED_MARKER}` is an autogen scaffold marker. "
     "Replace with a real theorem in THSD vocabulary (CLAUDE.md §12)."),
    ("trivial_obligation",
     re.compile(r":\s*True\s*:=\s*(?:by\s+trivial|True\.intro)\b"),
     "trivial `: True := by trivial` / `: True := True.intro` obligation "
     "is banned (CLAUDE.md §12.2 — restate using THSD vocabulary)."),
)


def _strip_comments(src: str) -> str:
    """Remove Lean comments so static lint doesn't false-positive on
    `sorry` / `admit` / `Unimplemented` words mentioned in docstrings.

    Lean 4 comment syntax:
      * ``-- single-line``
      * ``/- block comment -/``  (nested ``/-`` not handled; rare in
        autogen scaffolds and our hand-written proofs).
    """
    # Strip block comments first (non-greedy).
    src = re.sub(r"/-.*?-/", " ", src, flags=re.DOTALL)
    # Strip line comments.
    src = re.sub(r"--[^\n]*", " ", src)
    return src


def static_lint_lean_proof(lean_file: Union[str, Path]) -> List[str]:
    """Run Python-only static lint over a ``.lean`` file.

    Returns a list of error messages; empty list means the file
    satisfies the CLAUDE.md §12 ban on ``sorry`` / ``admit`` /
    autogen scaffold markers. The lint is intentionally cheap so it
    can run in every ``verify_lean_proof`` call regardless of
    whether the Lean toolchain is on PATH.

    Args:
        lean_file: path to the proof file.

    Returns:
        A list of human-readable lint error messages, one per
        violation. The order matches :data:`_STATIC_LINT_PATTERNS`
        but files with multiple violations of the same pattern get
        one entry per occurrence so the caller can count them.
    """
    path = Path(lean_file)
    if not path.is_file():
        return [f"file not found: {path}"]
    src = path.read_text(encoding="utf-8")
    stripped = _strip_comments(src)
    errs: List[str] = []
    for name, pattern, msg in _STATIC_LINT_PATTERNS:
        for match in pattern.finditer(stripped):
            # Report the line number in the ORIGINAL source for
            # human-friendly diagnostics.
            offset = match.start()
            stripped_prefix = stripped[:offset]
            # The stripped prefix has the same line breaks as the
            # original since we replaced comments with spaces; so we
            # can count newlines directly.
            line_no = stripped_prefix.count("\n") + 1
            errs.append(f"line {line_no}: [{name}] {msg}")
    return errs


def verify_lean_proof(lean_file: Union[str, Path],
                      *, timeout: float = 60.0) -> LeanVerdict:
    """Verify a single ``.lean`` file.

    Two-phase verification (CLAUDE.md §12):

      1. **Static lint** (always runs) — scans for ``sorry`` /
         ``admit`` / autogen scaffold markers. A violation produces
         ``status="error"`` immediately; the Lean toolchain is not
         even invoked.

      2. **Kernel check** (only when ``lean`` is on PATH) — shells
         out to ``lean --json`` (or ``lake env lean --json`` when
         the file imports ``Brian.Core``) and parses the verdict.

    Args:
        lean_file: path to the proof file.
        timeout:   seconds to allow Lean to complete (default 60s).

    Returns:
        :class:`LeanVerdict` summarising the outcome. Never raises —
        a missing binary, missing file, timeout, or Lean crash all
        map to a structured verdict the caller can inspect.
    """
    file_str = str(lean_file)
    path = Path(file_str)

    # Phase 1 — static lint (always runs).
    lint_errors = static_lint_lean_proof(file_str)
    if lint_errors:
        # Count `sorry` occurrences for the verdict.n_sorry field.
        n_sorry = sum(1 for e in lint_errors if "[sorry]" in e)
        return LeanVerdict(status="error", file=file_str,
                           errors=lint_errors, n_sorry=n_sorry)

    # Phase 2 — kernel check.
    lean = _lean_binary()
    if not lean:
        return LeanVerdict(status="skipped", file=file_str,
                           warnings=["lean binary not on PATH; "
                                     "static lint passed"])

    if not path.is_file():
        # static_lint would already have caught this, but be defensive.
        return LeanVerdict(status="error", file=file_str,
                           errors=[f"file not found: {file_str}"])

    # Prefer `lake env lean` when the file imports Brian.Core (it
    # needs LEAN_PATH set to the Brian library). Fall back to plain
    # `lean` for files that don't depend on Brian.
    needs_brian = "import Brian" in path.read_text(encoding="utf-8")
    lake = _lake_binary()
    brian_root = _brian_lean_root()
    if needs_brian and lake and brian_root.is_dir():
        cmd = [lake, "env", "lean", "--json", file_str]
        cwd = str(brian_root)
    else:
        cmd = [lean, "--json", file_str]
        cwd = None

    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=timeout, cwd=cwd,
        )
    except subprocess.TimeoutExpired:
        return LeanVerdict(status="error", file=file_str,
                           errors=[f"lean timed out after {timeout}s"])
    except OSError as exc:
        return LeanVerdict(status="error", file=file_str,
                           errors=[f"lean invocation failed: {exc}"])

    errors: List[str] = []
    warnings: List[str] = []
    n_sorry = 0
    for line in (proc.stdout or "").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        sev = (obj.get("severity") or "").lower()
        msg = obj.get("data") or obj.get("message") or ""
        text_lower = (msg if isinstance(msg, str) else json.dumps(msg)).lower()
        if "sorry" in text_lower or "declaration uses 'sorry'" in text_lower:
            n_sorry += 1
        if sev == "error":
            errors.append(text_lower)
        elif sev == "warning":
            warnings.append(text_lower)

    # Lint already verified the source has no raw `sorry` tokens, but
    # keep the kernel's reported count as a sanity floor.
    if proc.returncode != 0 or errors:
        return LeanVerdict(status="error", file=file_str,
                           errors=errors or [f"lean exit {proc.returncode}"],
                           warnings=warnings, n_sorry=n_sorry)
    if n_sorry > 0:
        return LeanVerdict(status="compiles", file=file_str,
                           warnings=warnings, n_sorry=n_sorry)
    return LeanVerdict(status="verified", file=file_str,
                       warnings=warnings, n_sorry=0)
