# -*- coding: utf-8 -*-
"""Lean proof emission + verification backend.

Two responsibilities:

1. :func:`emit_hypothesis_proof` / :func:`emit_discovery_proof` — generate
   a ``.lean`` proof stub from a record. The stub declares the canonical
   theorem (``theorem_name``), brings the relevant Brian Lean library
   into scope, encodes the obligation as a ``Prop``, and ends in
   ``sorry`` until the human or a Lean tactic discharges it.

2. :func:`verify_lean_proof` — shell out to ``lean --json <file>`` (if a
   ``lean`` binary is on PATH) and return a structured
   :class:`LeanVerdict`. Without the binary the function returns
   ``LeanVerdict(status="skipped")`` so callers can keep moving — the
   record's ``proof_status`` stays at ``"stub"`` until verification
   succeeds elsewhere.

The Lean library namespace is ``Brian.*``; each hypothesis or discovery
gets a unique theorem name like ``Brian.PhiMonotone`` (hypothesis) or
``Brian.Discoveries.D001_NoRegression``. The emitter does *not* try to
write the actual mathematical proof; it lays out the obligation in a
form a Lean tactician (or, later, an automated tactic) can attack.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Union

from neuroslm.discoveries.records import (
    HypothesisRecord, DiscoveryRecord,
)


# ── verdict ────────────────────────────────────────────────────────


@dataclass
class LeanVerdict:
    """Outcome of a single :func:`verify_lean_proof` call.

    Status semantics:
      ``verified``  — Lean accepted the file with 0 errors AND no
                      ``sorry`` remains
      ``compiles``  — Lean accepted the file with 0 errors BUT one or
                      more ``sorry`` remain — kernel didn't reject
                      anything but the obligations are still open
      ``error``     — Lean reported one or more errors
      ``skipped``   — Lean binary not on PATH (or refused to run)
    """
    status: str
    file: str = ""
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    n_sorry: int = 0

    def proof_status_for_record(self) -> str:
        """Map the Lean verdict back to the record's
        :data:`PROOF_STATUSES` vocabulary."""
        return {
            "verified": "verified",
            "compiles": "compiles",
            "error":    "stub",      # the file exists, just doesn't go through
            "skipped":  "stub",
        }.get(self.status, "stub")


# ── emission helpers ───────────────────────────────────────────────


def _lean_header_block() -> str:
    """Common imports + module preamble for every Brian Lean file."""
    return (
        "/-\n"
        "  Brian — autogenerated Lean proof obligation.\n"
        "  Edit by hand to discharge `sorry`. Re-run\n"
        "  `python -m neuroslm.discoveries.lean` to regenerate the stub\n"
        "  (only the body inside the `theorem ... := by sorry` block will\n"
        "  be overwritten; comments and manual proof tactics survive\n"
        "  via the source-map preservation contract in records.py).\n"
        "-/\n"
        "import Mathlib.Tactic\n"
        "-- import Brian.Core      -- planned (formal_framework.md §10.2)\n"
        "\n"
    )


def _format_metric_block(label: str, metrics: Dict[str, float]) -> str:
    """Render a fitness dict as a Lean comment block — kept verbatim
    in the proof so the kernel can be pointed at the empirical premise
    even before the Brian library models it as a structure."""
    lines = [f"  {label}:"]
    for k in sorted(metrics):
        lines.append(f"    {k} := {metrics[k]}")
    return "\n".join(lines)


def _emit_proof_text(*,
                     record_id: str,
                     theorem_name: str,
                     headline_md: str,
                     obligation_lean: str,
                     extra_comments: Optional[str] = None) -> str:
    """Assemble the final Lean file contents from common parts."""
    sections: List[str] = [_lean_header_block()]
    sections.append(
        f"/-\n  Record: {record_id}\n"
        f"  Obligation (Markdown):\n"
        f"{_indent_md(headline_md, 4)}\n"
        f"-/\n"
    )
    if extra_comments:
        sections.append(f"/-\n{_indent_md(extra_comments, 2)}\n-/\n")
    # `noncomputable` so we can use real-valued definitions without
    # demanding computability proofs; `@[simp]` not added — only the
    # tactician should opt into the simp set later.
    sections.append(
        f"noncomputable section\n\n"
        f"namespace {_namespace_of(theorem_name)}\n\n"
        f"-- The obligation, restated in Lean syntax. The proof body\n"
        f"-- below is a `sorry` placeholder; replace it with the\n"
        f"-- actual tactics once the supporting lemmas land.\n"
        f"{obligation_lean}\n\n"
        f"end {_namespace_of(theorem_name)}\n\n"
        f"end\n"
    )
    return "".join(sections)


def _namespace_of(theorem_name: str) -> str:
    """``Brian.PhiMonotone`` → ``Brian``; ``Brian.Discoveries.D001_X`` →
    ``Brian.Discoveries``."""
    parts = theorem_name.split(".")
    if len(parts) < 2:
        return "Brian"
    return ".".join(parts[:-1])


def _theorem_leaf(theorem_name: str) -> str:
    """The unqualified theorem name — last dotted component."""
    return theorem_name.rsplit(".", 1)[-1]


def _indent_md(text: str, n: int) -> str:
    pad = " " * n
    return "\n".join(pad + line for line in (text or "").splitlines())


# ── public: emit from a hypothesis ─────────────────────────────────


def emit_hypothesis_proof(record: HypothesisRecord,
                          root: Union[str, Path]) -> str:
    """Emit a Lean proof stub for ``record`` under ``<root>/proofs/``.

    Args:
        record: the hypothesis record (will be mutated:
                ``proof_path`` and ``proof_status`` are set).
        root:   the hypothesis directory (the function will create
                ``proofs/`` if it doesn't exist).

    Returns:
        Absolute path to the written ``.lean`` file.
    """
    root = Path(root)
    proofs_dir = root / "proofs"
    proofs_dir.mkdir(parents=True, exist_ok=True)
    out_path = proofs_dir / record.proof_filename()

    leaf = _theorem_leaf(record.theorem_name)
    obligation = (
        f"theorem {leaf}\n"
        f"    -- TODO(brian): add hypotheses as the Brian library lands\n"
        f"    : True := by\n"
        f"  -- Mechanised proof obligation for hypothesis {record.id}.\n"
        f"  -- Replace `sorry` once the supporting lemmas are in scope.\n"
        f"  sorry"
    )

    text = _emit_proof_text(
        record_id=record.id,
        theorem_name=record.theorem_name,
        headline_md=record.statement_md,
        obligation_lean=obligation,
        extra_comments=(
            f"References:\n"
            + "\n".join(f"  - {r}" for r in (record.references or [])) + "\n"
            + "Code refs:\n"
            + "\n".join(f"  - {c}" for c in (record.code_refs or [])) + "\n"
            + "Test refs:\n"
            + "\n".join(f"  - {t}" for t in (record.test_refs or []))
        ) if (record.references or record.code_refs or record.test_refs)
            else None,
    )
    out_path.write_text(text, encoding="utf-8")

    # ``proof_path`` is stored as a POSIX-style relative path so the
    # value round-trips identically on Windows, Linux, and macOS — the
    # field lives in checked-in YAML front-matter and needs to be
    # filesystem-portable.
    record.proof_path = _posix_relative(out_path, root.parent)
    record.proof_status = "stub"
    return str(out_path.resolve())


def _posix_relative(target: Path, base: Path) -> str:
    """``target`` expressed relative to ``base``, with ``/`` separators."""
    try:
        return target.resolve().relative_to(base.resolve()).as_posix()
    except ValueError:
        # ``target`` is not under ``base`` — fall back to the absolute
        # POSIX form so the field stays parseable.
        return target.resolve().as_posix()


# ── public: emit from a discovery ──────────────────────────────────


def emit_discovery_proof(record: DiscoveryRecord,
                         root: Union[str, Path]) -> str:
    """Emit a Lean proof stub for an autodiscovered mutation.

    The obligation we encode is *"this mutation does not regress any
    fitness coordinate the gates care about"* — a no-regression
    monotonicity claim, restated in Lean as a ``≤``-ordering over the
    fitness map. Until the Brian Lean library models the fitness
    structure formally the body is a ``sorry``; the metric values are
    kept in a comment so the human (or a later tactic) has the
    empirical premise to hand.
    """
    root = Path(root)
    proofs_dir = root / "proofs"
    proofs_dir.mkdir(parents=True, exist_ok=True)
    out_path = proofs_dir / record.proof_filename()

    leaf = _theorem_leaf(record.theorem_name)

    obligation = (
        f"theorem {leaf}\n"
        f"    -- Parent genome: {record.parent_dna_id}\n"
        f"    -- Mutation chain: {', '.join(record.mutation_chain)}\n"
        f"    : True := by\n"
        f"  -- No-regression obligation for discovery {record.id}.\n"
        f"  -- For every fitness coordinate, after ≤ before (for cost-like\n"
        f"  -- metrics) or after ≥ before (for benefit-like metrics).\n"
        f"  -- Empirical witness (raw values):\n"
        f"{_format_metric_block('before', record.fitness_before)}\n"
        f"{_format_metric_block('after',  record.fitness_after)}\n"
        f"{_format_metric_block('delta',  record.fitness_delta)}\n"
        f"  sorry"
    )

    headline = (
        record.mechanism_md.strip()
        + "\n\nObservation: " + ", ".join(
            f"{k}: {record.fitness_before.get(k, 0.0):.3f} -> "
            f"{record.fitness_after.get(k, 0.0):.3f}"
            for k in sorted(set(record.fitness_before) | set(record.fitness_after))
        )
    )
    text = _emit_proof_text(
        record_id=record.id,
        theorem_name=record.theorem_name,
        headline_md=headline,
        obligation_lean=obligation,
        extra_comments=(
            f"Generation: {record.generation}\n"
            f"Mutation chain: {', '.join(record.mutation_chain)}"
        ),
    )
    out_path.write_text(text, encoding="utf-8")
    record.proof_path = _posix_relative(out_path, root.parent)
    record.proof_status = "stub"
    return str(out_path.resolve())


# ── public: verify ─────────────────────────────────────────────────


def _lean_binary() -> Optional[str]:
    """Return the path to the ``lean`` binary, or ``None`` if absent.

    Indirected so tests can monkeypatch it to simulate a no-Lean worker.
    """
    return shutil.which("lean")


def verify_lean_proof(lean_file: Union[str, Path],
                      *, timeout: float = 60.0) -> LeanVerdict:
    """Verify a single ``.lean`` file by shelling out to ``lean --json``.

    Args:
        lean_file: path to the proof file.
        timeout:   seconds to allow Lean to complete (default 60s).

    Returns:
        :class:`LeanVerdict` summarising the outcome. Never raises — a
        missing binary, missing file, timeout, or Lean crash all map to
        a structured verdict the caller can inspect.
    """
    file_str = str(lean_file)
    lean = _lean_binary()
    if not lean:
        return LeanVerdict(status="skipped", file=file_str,
                           warnings=["lean binary not on PATH"])

    path = Path(file_str)
    if not path.is_file():
        return LeanVerdict(status="error", file=file_str,
                           errors=[f"file not found: {file_str}"])

    try:
        proc = subprocess.run(
            [lean, "--json", file_str],
            capture_output=True, text=True, timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return LeanVerdict(status="error", file=file_str,
                           errors=[f"lean timed out after {timeout}s"])
    except OSError as exc:
        return LeanVerdict(status="error", file=file_str,
                           errors=[f"lean invocation failed: {exc}"])

    errors: List[str] = []
    warnings: List[str] = []
    n_sorry = 0
    for line in (proc.stdout or "").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        sev = (obj.get("severity") or "").lower()
        msg = obj.get("data") or obj.get("message") or ""
        text_lower = (msg if isinstance(msg, str) else json.dumps(msg)).lower()
        if "sorry" in text_lower or "declaration uses 'sorry'" in text_lower:
            n_sorry += 1
        if sev == "error":
            errors.append(text_lower)
        elif sev == "warning":
            warnings.append(text_lower)

    # Also scan the file for `sorry` tokens so unexecuted theorems still
    # count — `lean --json` only flags reachable obligations.
    try:
        src = path.read_text(encoding="utf-8")
        n_sorry = max(n_sorry, len(re.findall(r"\bsorry\b", src)))
    except OSError:
        pass

    if proc.returncode != 0 or errors:
        return LeanVerdict(status="error", file=file_str,
                           errors=errors or [f"lean exit {proc.returncode}"],
                           warnings=warnings, n_sorry=n_sorry)
    if n_sorry > 0:
        return LeanVerdict(status="compiles", file=file_str,
                           warnings=warnings, n_sorry=n_sorry)
    return LeanVerdict(status="verified", file=file_str,
                       warnings=warnings, n_sorry=0)
