/-
  Brian — autogenerated Lean proof obligation.
  Edit by hand to discharge `sorry`. Re-run
  `python -m neuroslm.discoveries.lean` to regenerate the stub
  (only the body inside the `theorem ... := by sorry` block will
  be overwritten; comments and manual proof tactics survive
  via the source-map preservation contract in records.py).
-/
import Mathlib.Tactic
-- import Brian.Core      -- planned (formal_framework.md §10.2)

/-
  Record: H002
  Obligation (Markdown):
    **Statement.** Let $L_{\text{base}}$ be the base training loss and $\mathrm{CDGA}$ the Cross-Distribution Gradient Alignment term (``docs/CDGA.md``, $\lambda \ge 0$). Then
    
    $$\Delta_{\mathrm{OOD}}(\theta + \lambda\cdot\mathrm{CDGA}) \;\le\; \Delta_{\mathrm{OOD}}(\theta)$$
    
    where $\Delta_{\mathrm{OOD}} = L_{\text{OOD}} - L_{\text{ID}}$ is the OOD generalisation gap.
    
    **Why it matters.** Adds a free generalisation guarantee: turning on the CDGA term never widens the OOD gap, even when it doesn't help. The empirical version is exercised in ``test_cdga_smoke.py``.
-/
/-
  References:
    - formal_framework.md §10.2
    - docs/CDGA.md
  Code refs:
    - neuroslm/regularizers.py
  Test refs:
    - tests/test_cdga_smoke.py
-/
noncomputable section

namespace Brian

-- The obligation, restated in Lean syntax. The proof body
-- below is a `sorry` placeholder; replace it with the
-- actual tactics once the supporting lemmas land.
theorem OodGapDecrease
    -- TODO(brian): add hypotheses as the Brian library lands
    : True := by
  -- Mechanised proof obligation for hypothesis H002.
  -- Replace `sorry` once the supporting lemmas are in scope.
  sorry

end Brian

end
