/-
  Brian — autogenerated Lean proof obligation.
  Edit by hand to discharge `sorry`. Re-run
  `python -m neuroslm.discoveries.lean` to regenerate the stub
  (only the body inside the `theorem ... := by sorry` block will
  be overwritten; comments and manual proof tactics survive
  via the source-map preservation contract in records.py).
-/
import Mathlib.Tactic
-- import Brian.Core      -- planned (formal_framework.md §10.2)

/-
  Record: H005
  Obligation (Markdown):
    **Statement.** Given samples $X \sim \mathcal{D}_{\text{before}}$, $Y \sim \mathcal{D}_{\text{after}}$ and a one-sided Welch's $t$-test $T(X, Y)$, ``ImprovementGate.admit(X, Y, direction='decrease', alpha, min_effect)`` returns ``True`` iff
    
    $$T(X, Y) < t_\alpha \;\wedge\; |\mathbb{E}[Y] - \mathbb{E}[X]| / |\mathbb{E}[X]| \ge \mathrm{min\_effect}$$
    
    and the direction-of-effect predicate holds.
    
    **Why it matters.** The statistical admission criterion is the current default backend behind the gate; the Lean proof formalises that the Python implementation matches the textbook one-sided Welch test up to a (provable) threshold-comparison wrapper.
-/
/-
  References:
    - formal_framework.md §9
    - formal_framework.md §10.2
  Code refs:
    - neuroslm/verification/improvement_gate.py
  Test refs:
    - tests/verification/test_improvement_gate.py
-/
noncomputable section

namespace Brian

-- The obligation, restated in Lean syntax. The proof body
-- below is a `sorry` placeholder; replace it with the
-- actual tactics once the supporting lemmas land.
theorem ImprovementGateWelch
    -- TODO(brian): add hypotheses as the Brian library lands
    : True := by
  -- Mechanised proof obligation for hypothesis H005.
  -- Replace `sorry` once the supporting lemmas are in scope.
  sorry

end Brian

end
