# -*- coding: utf-8 -*-
"""Neural Flow Graph for the rcc_bowtie architecture.

Auto-generated by `brian compile nfg`. Load with:
    from nfg import NFG
    # NFG['nodes'], NFG['edges'], NFG['stats']
"""
NFG = {
  "arch": "rcc_bowtie",
  "stats": {
    "n_populations": 28,
    "n_neurotransmitters": 7,
    "n_synapses": 19,
    "n_modulations": 17
  },
  "nodes": [
    {
      "name": "sensory",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "association",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "thalamus",
      "kind": "pop",
      "op": "gated",
      "equation": "y = ReLU(x) * sigmoid(gate)",
      "properties": {
        "count": 256,
        "dynamics": "gated"
      }
    },
    {
      "name": "world",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "self_m",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "amygdala",
      "kind": "pop",
      "op": "ode",
      "equation": "dV/dt = (-V + x) / tau",
      "properties": {
        "count": 32,
        "dynamics": "integrate_and_fire"
      }
    },
    {
      "name": "insula",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 64,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "qualia",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "gws",
      "kind": "pop",
      "op": "softmax",
      "equation": "y = softmax(x / 0.1) * d_sem",
      "properties": {
        "count": 256,
        "dynamics": "winner_take_all"
      }
    },
    {
      "name": "neural_geometry",
      "kind": "pop",
      "op": "linear",
      "equation": "y = x",
      "properties": {
        "count": 256,
        "dynamics": "static"
      }
    },
    {
      "name": "hippo",
      "kind": "pop",
      "op": "relu",
      "equation": "y = (1 - alpha) * s + alpha * ReLU(x)",
      "properties": {
        "count": 4096,
        "dynamics": "attractor_network"
      }
    },
    {
      "name": "entorhinal",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "cerebellum",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "pfc",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "acc",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "bg",
      "kind": "pop",
      "op": "softmax",
      "equation": "y = softmax(x / 0.1) * d_sem",
      "properties": {
        "count": 256,
        "dynamics": "winner_take_all"
      }
    },
    {
      "name": "forward_m",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "evaluator",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "dmn",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "thought_transformer",
      "kind": "pop",
      "op": "softmax_relu",
      "equation": "y = softmax(x) * ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "attention_pool"
      }
    },
    {
      "name": "claustrum",
      "kind": "pop",
      "op": "gated",
      "equation": "y = ReLU(x) * sigmoid(gate)",
      "properties": {
        "count": 256,
        "dynamics": "gated"
      }
    },
    {
      "name": "motor",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "vta",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 64,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "nucleus_accumbens",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 64,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "locus_coeruleus",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 32,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "raphe_nuclei",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 48,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "nucleus_basalis",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 32,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "substantia_nigra",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 64,
        "dynamics": "rate_code"
      }
    },
    {
      "name": "dopamine",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.1,
        "release": 0.2,
        "reuptake": 0.8
      }
    },
    {
      "name": "norepinephrine",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.15,
        "release": 0.3,
        "reuptake": 0.7
      }
    },
    {
      "name": "serotonin",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.3,
        "release": 0.05,
        "reuptake": 0.95
      }
    },
    {
      "name": "acetylcholine",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.2,
        "release": 0.25,
        "reuptake": 0.75
      }
    },
    {
      "name": "endocannabinoid",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.05,
        "release": 0.4,
        "reuptake": 0.6
      }
    },
    {
      "name": "glutamate",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.4,
        "release": 0.5,
        "reuptake": 0.5
      }
    },
    {
      "name": "gaba",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.1,
        "release": 0.1,
        "reuptake": 0.9
      }
    }
  ],
  "edges": [
    {
      "src": "thalamus",
      "tgt": "gws",
      "kind": "synapse",
      "weight": 0.8,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "world",
      "tgt": "gws",
      "kind": "synapse",
      "weight": 0.6,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "self_m",
      "tgt": "gws",
      "kind": "synapse",
      "weight": 0.6,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "gws",
      "tgt": "hippo",
      "kind": "synapse",
      "weight": 0.7,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "gws",
      "tgt": "pfc",
      "kind": "synapse",
      "weight": 0.8,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "gws",
      "tgt": "acc",
      "kind": "synapse",
      "weight": 0.7,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "pfc",
      "tgt": "bg",
      "kind": "synapse",
      "weight": 0.6,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "bg",
      "tgt": "motor",
      "kind": "synapse",
      "weight": 0.8,
      "nt": "gaba",
      "effect": null
    },
    {
      "src": "forward_m",
      "tgt": "evaluator",
      "kind": "synapse",
      "weight": 0.7,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "hippo",
      "tgt": "pfc",
      "kind": "synapse",
      "weight": 0.5,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "entorhinal",
      "tgt": "pfc",
      "kind": "synapse",
      "weight": 0.4,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "pfc",
      "tgt": "thalamus",
      "kind": "synapse",
      "weight": 0.3,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "dmn",
      "tgt": "gws",
      "kind": "synapse",
      "weight": 0.5,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "cerebellum",
      "tgt": "forward_m",
      "kind": "synapse",
      "weight": 0.6,
      "nt": "gaba",
      "effect": null
    },
    {
      "src": "motor",
      "tgt": "sensory",
      "kind": "synapse",
      "weight": 0.4,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "pfc",
      "tgt": "reasoning_cortex",
      "kind": "synapse",
      "weight": 0.5,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "reasoning_cortex",
      "tgt": "motor",
      "kind": "synapse",
      "weight": 0.5,
      "nt": "glutamate",
      "effect": null
    },
    {
      "src": "dmn",
      "tgt": "reasoning_cortex",
      "kind": "synapse",
      "weight": 0.3,
      "nt": "gaba",
      "effect": null
    },
    {
      "src": "reasoning_cortex",
      "tgt": "dmn",
      "kind": "synapse",
      "weight": 0.3,
      "nt": "gaba",
      "effect": null
    },
    {
      "src": "dopamine",
      "tgt": "pfc",
      "kind": "modulation",
      "weight": 0.6,
      "nt": "dopamine",
      "effect": "multiplicative"
    },
    {
      "src": "serotonin",
      "tgt": "pfc",
      "kind": "modulation",
      "weight": 0.3,
      "nt": "serotonin",
      "effect": "additive"
    },
    {
      "src": "acetylcholine",
      "tgt": "pfc",
      "kind": "modulation",
      "weight": 0.4,
      "nt": "acetylcholine",
      "effect": "multiplicative"
    },
    {
      "src": "gaba",
      "tgt": "pfc",
      "kind": "modulation",
      "weight": 0.4,
      "nt": "gaba",
      "effect": "multiplicative"
    },
    {
      "src": "acetylcholine",
      "tgt": "hippo",
      "kind": "modulation",
      "weight": 0.5,
      "nt": "acetylcholine",
      "effect": "multiplicative"
    },
    {
      "src": "glutamate",
      "tgt": "hippo",
      "kind": "modulation",
      "weight": 0.4,
      "nt": "glutamate",
      "effect": "additive"
    },
    {
      "src": "dopamine",
      "tgt": "bg",
      "kind": "modulation",
      "weight": 0.7,
      "nt": "dopamine",
      "effect": "multiplicative"
    },
    {
      "src": "gaba",
      "tgt": "bg",
      "kind": "modulation",
      "weight": 0.5,
      "nt": "gaba",
      "effect": "multiplicative"
    },
    {
      "src": "norepinephrine",
      "tgt": "thalamus",
      "kind": "modulation",
      "weight": 0.5,
      "nt": "norepinephrine",
      "effect": "multiplicative"
    },
    {
      "src": "gaba",
      "tgt": "thalamus",
      "kind": "modulation",
      "weight": 0.3,
      "nt": "gaba",
      "effect": "multiplicative"
    },
    {
      "src": "acetylcholine",
      "tgt": "sensory",
      "kind": "modulation",
      "weight": 0.3,
      "nt": "acetylcholine",
      "effect": "multiplicative"
    },
    {
      "src": "endocannabinoid",
      "tgt": "sensory",
      "kind": "modulation",
      "weight": 0.3,
      "nt": "endocannabinoid",
      "effect": "multiplicative"
    },
    {
      "src": "serotonin",
      "tgt": "dmn",
      "kind": "modulation",
      "weight": 0.6,
      "nt": "serotonin",
      "effect": "multiplicative"
    },
    {
      "src": "acetylcholine",
      "tgt": "dmn",
      "kind": "modulation",
      "weight": 0.2,
      "nt": "acetylcholine",
      "effect": "multiplicative"
    },
    {
      "src": "dopamine",
      "tgt": "gws",
      "kind": "modulation",
      "weight": 0.5,
      "nt": "dopamine",
      "effect": "additive"
    },
    {
      "src": "serotonin",
      "tgt": "amygdala",
      "kind": "modulation",
      "weight": 0.7,
      "nt": "serotonin",
      "effect": "multiplicative"
    },
    {
      "src": "dopamine",
      "tgt": "acc",
      "kind": "modulation",
      "weight": 0.5,
      "nt": "dopamine",
      "effect": "multiplicative"
    }
  ]
}
