# -*- coding: utf-8 -*-
"""Neural Flow Graph for the rcc_bowtie architecture.

Auto-generated by `brian compile nfg`. Load with:
    from nfg import NFG
    # NFG['nodes'], NFG['edges'], NFG['stats'], NFG['nt_systems'], ...
"""
NFG = {
  "arch": "rcc_bowtie",
  "architecture_meta": {
    "name": "rcc_bowtie",
    "properties": {
      "d_sem": "256",
      "dt": "0.01"
    }
  },
  "stats": {
    "n_populations": 29,
    "n_neurotransmitters": 7,
    "n_synapses": 19,
    "n_modulations": 17
  },
  "nodes": [
    {
      "name": "sensory",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.005,
        "output_dim": null
      }
    },
    {
      "name": "association",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.01,
        "output_dim": null
      }
    },
    {
      "name": "thalamus",
      "kind": "pop",
      "op": "gated",
      "equation": "y = ReLU(x) * sigmoid(gate)",
      "properties": {
        "count": 256,
        "dynamics": "gated",
        "timescale": 0.01,
        "output_dim": null
      }
    },
    {
      "name": "world",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.05,
        "output_dim": null
      }
    },
    {
      "name": "self_m",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.05,
        "output_dim": null
      }
    },
    {
      "name": "amygdala",
      "kind": "pop",
      "op": "ode",
      "equation": "dV/dt = (-V + x) / tau",
      "properties": {
        "count": 32,
        "dynamics": "integrate_and_fire",
        "timescale": 0.005,
        "output_dim": null
      }
    },
    {
      "name": "insula",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 64,
        "dynamics": "rate_code",
        "timescale": 0.02,
        "output_dim": null
      }
    },
    {
      "name": "qualia",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.02,
        "output_dim": null
      }
    },
    {
      "name": "gws",
      "kind": "pop",
      "op": "softmax",
      "equation": "y = softmax(x / 0.1) * d_sem",
      "properties": {
        "count": 256,
        "dynamics": "winner_take_all",
        "timescale": 0.02,
        "output_dim": null
      }
    },
    {
      "name": "neural_geometry",
      "kind": "pop",
      "op": "linear",
      "equation": "y = x",
      "properties": {
        "count": 256,
        "dynamics": "static",
        "timescale": 0.001,
        "output_dim": null
      }
    },
    {
      "name": "hippo",
      "kind": "pop",
      "op": "relu",
      "equation": "y = (1 - alpha) * s + alpha * ReLU(x)",
      "properties": {
        "count": 4096,
        "dynamics": "attractor_network",
        "timescale": 0.1,
        "output_dim": null
      }
    },
    {
      "name": "entorhinal",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.05,
        "output_dim": null
      }
    },
    {
      "name": "cerebellum",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.005,
        "output_dim": null
      }
    },
    {
      "name": "pfc",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.02,
        "output_dim": null
      }
    },
    {
      "name": "acc",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.02,
        "output_dim": null
      }
    },
    {
      "name": "bg",
      "kind": "pop",
      "op": "softmax",
      "equation": "y = softmax(x / 0.1) * d_sem",
      "properties": {
        "count": 256,
        "dynamics": "winner_take_all",
        "timescale": 0.01,
        "output_dim": null
      }
    },
    {
      "name": "forward_m",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.02,
        "output_dim": null
      }
    },
    {
      "name": "evaluator",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.01,
        "output_dim": null
      }
    },
    {
      "name": "dmn",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.1,
        "output_dim": null
      }
    },
    {
      "name": "thought_transformer",
      "kind": "pop",
      "op": "softmax_relu",
      "equation": "y = softmax(x) * ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "attention_pool",
        "timescale": 0.02,
        "output_dim": null
      }
    },
    {
      "name": "claustrum",
      "kind": "pop",
      "op": "gated",
      "equation": "y = ReLU(x) * sigmoid(gate)",
      "properties": {
        "count": 256,
        "dynamics": "gated",
        "timescale": 0.01,
        "output_dim": null
      }
    },
    {
      "name": "motor",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "rate_code",
        "timescale": 0.005,
        "output_dim": null
      }
    },
    {
      "name": "vta",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 64,
        "dynamics": "rate_code",
        "timescale": 0.02,
        "output_dim": null
      }
    },
    {
      "name": "nucleus_accumbens",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 64,
        "dynamics": "rate_code",
        "timescale": 0.01,
        "output_dim": null
      }
    },
    {
      "name": "locus_coeruleus",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 32,
        "dynamics": "rate_code",
        "timescale": 0.02,
        "output_dim": null
      }
    },
    {
      "name": "raphe_nuclei",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 48,
        "dynamics": "rate_code",
        "timescale": 0.05,
        "output_dim": null
      }
    },
    {
      "name": "nucleus_basalis",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 32,
        "dynamics": "rate_code",
        "timescale": 0.02,
        "output_dim": null
      }
    },
    {
      "name": "substantia_nigra",
      "kind": "pop",
      "op": "relu",
      "equation": "y = ReLU(x)",
      "properties": {
        "count": 64,
        "dynamics": "rate_code",
        "timescale": 0.01,
        "output_dim": null
      }
    },
    {
      "name": "reasoning_cortex",
      "kind": "pop",
      "op": "softmax_relu",
      "equation": "y = softmax(x) * ReLU(x)",
      "properties": {
        "count": 256,
        "dynamics": "attention_pool",
        "timescale": 0.02,
        "output_dim": null
      }
    },
    {
      "name": "dopamine",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.1,
        "release": 0.2,
        "reuptake": 0.8,
        "diffusion": 0.02
      }
    },
    {
      "name": "norepinephrine",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.15,
        "release": 0.3,
        "reuptake": 0.7,
        "diffusion": 0.015
      }
    },
    {
      "name": "serotonin",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.3,
        "release": 0.05,
        "reuptake": 0.95,
        "diffusion": 0.01
      }
    },
    {
      "name": "acetylcholine",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.2,
        "release": 0.25,
        "reuptake": 0.75,
        "diffusion": 0.025
      }
    },
    {
      "name": "endocannabinoid",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.05,
        "release": 0.4,
        "reuptake": 0.6,
        "diffusion": 0.03
      }
    },
    {
      "name": "glutamate",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.4,
        "release": 0.5,
        "reuptake": 0.5,
        "diffusion": 0.02
      }
    },
    {
      "name": "gaba",
      "kind": "nt",
      "op": "nt_dynamics",
      "equation": null,
      "properties": {
        "base": 0.1,
        "release": 0.1,
        "reuptake": 0.9,
        "diffusion": 0.01
      }
    }
  ],
  "edges": [
    {
      "src": "thalamus",
      "tgt": "gws",
      "kind": "synapse",
      "weight": 0.8,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "world",
      "tgt": "gws",
      "kind": "synapse",
      "weight": 0.6,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "self_m",
      "tgt": "gws",
      "kind": "synapse",
      "weight": 0.6,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "gws",
      "tgt": "hippo",
      "kind": "synapse",
      "weight": 0.7,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "gws",
      "tgt": "pfc",
      "kind": "synapse",
      "weight": 0.8,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "gws",
      "tgt": "acc",
      "kind": "synapse",
      "weight": 0.7,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "pfc",
      "tgt": "bg",
      "kind": "synapse",
      "weight": 0.6,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "bg",
      "tgt": "motor",
      "kind": "synapse",
      "weight": 0.8,
      "nt": "gaba",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "forward_m",
      "tgt": "evaluator",
      "kind": "synapse",
      "weight": 0.7,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "hippo",
      "tgt": "pfc",
      "kind": "synapse",
      "weight": 0.5,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "entorhinal",
      "tgt": "pfc",
      "kind": "synapse",
      "weight": 0.4,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "pfc",
      "tgt": "thalamus",
      "kind": "synapse",
      "weight": 0.3,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "dmn",
      "tgt": "gws",
      "kind": "synapse",
      "weight": 0.5,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "cerebellum",
      "tgt": "forward_m",
      "kind": "synapse",
      "weight": 0.6,
      "nt": "gaba",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "motor",
      "tgt": "sensory",
      "kind": "synapse",
      "weight": 0.4,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "pfc",
      "tgt": "reasoning_cortex",
      "kind": "synapse",
      "weight": 0.5,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "reasoning_cortex",
      "tgt": "motor",
      "kind": "synapse",
      "weight": 0.5,
      "nt": "glutamate",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "dmn",
      "tgt": "reasoning_cortex",
      "kind": "synapse",
      "weight": 0.3,
      "nt": "gaba",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "reasoning_cortex",
      "tgt": "dmn",
      "kind": "synapse",
      "weight": 0.3,
      "nt": "gaba",
      "effect": null,
      "equation": "@standard_synapse"
    },
    {
      "src": "dopamine",
      "tgt": "pfc",
      "kind": "modulation",
      "weight": 0.6,
      "nt": "dopamine",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "serotonin",
      "tgt": "pfc",
      "kind": "modulation",
      "weight": 0.3,
      "nt": "serotonin",
      "effect": "additive",
      "equation": "@additive_modulation"
    },
    {
      "src": "acetylcholine",
      "tgt": "pfc",
      "kind": "modulation",
      "weight": 0.4,
      "nt": "acetylcholine",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "gaba",
      "tgt": "pfc",
      "kind": "modulation",
      "weight": 0.4,
      "nt": "gaba",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "acetylcholine",
      "tgt": "hippo",
      "kind": "modulation",
      "weight": 0.5,
      "nt": "acetylcholine",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "glutamate",
      "tgt": "hippo",
      "kind": "modulation",
      "weight": 0.4,
      "nt": "glutamate",
      "effect": "additive",
      "equation": "@additive_modulation"
    },
    {
      "src": "dopamine",
      "tgt": "bg",
      "kind": "modulation",
      "weight": 0.7,
      "nt": "dopamine",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "gaba",
      "tgt": "bg",
      "kind": "modulation",
      "weight": 0.5,
      "nt": "gaba",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "norepinephrine",
      "tgt": "thalamus",
      "kind": "modulation",
      "weight": 0.5,
      "nt": "norepinephrine",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "gaba",
      "tgt": "thalamus",
      "kind": "modulation",
      "weight": 0.3,
      "nt": "gaba",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "acetylcholine",
      "tgt": "sensory",
      "kind": "modulation",
      "weight": 0.3,
      "nt": "acetylcholine",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "endocannabinoid",
      "tgt": "sensory",
      "kind": "modulation",
      "weight": 0.3,
      "nt": "endocannabinoid",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "serotonin",
      "tgt": "dmn",
      "kind": "modulation",
      "weight": 0.6,
      "nt": "serotonin",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "acetylcholine",
      "tgt": "dmn",
      "kind": "modulation",
      "weight": 0.2,
      "nt": "acetylcholine",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "dopamine",
      "tgt": "gws",
      "kind": "modulation",
      "weight": 0.5,
      "nt": "dopamine",
      "effect": "additive",
      "equation": "@additive_modulation"
    },
    {
      "src": "serotonin",
      "tgt": "amygdala",
      "kind": "modulation",
      "weight": 0.7,
      "nt": "serotonin",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    },
    {
      "src": "dopamine",
      "tgt": "acc",
      "kind": "modulation",
      "weight": 0.5,
      "nt": "dopamine",
      "effect": "multiplicative",
      "equation": "@multiplicative_modulation"
    }
  ],
  "nt_systems": [
    {
      "name": "dopamine",
      "base": 0.1,
      "release": 0.2,
      "reuptake": 0.8,
      "diffusion": 0.02,
      "used": true
    },
    {
      "name": "norepinephrine",
      "base": 0.15,
      "release": 0.3,
      "reuptake": 0.7,
      "diffusion": 0.015,
      "used": true
    },
    {
      "name": "serotonin",
      "base": 0.3,
      "release": 0.05,
      "reuptake": 0.95,
      "diffusion": 0.01,
      "used": true
    },
    {
      "name": "acetylcholine",
      "base": 0.2,
      "release": 0.25,
      "reuptake": 0.75,
      "diffusion": 0.025,
      "used": true
    },
    {
      "name": "endocannabinoid",
      "base": 0.05,
      "release": 0.4,
      "reuptake": 0.6,
      "diffusion": 0.03,
      "used": true
    },
    {
      "name": "glutamate",
      "base": 0.4,
      "release": 0.5,
      "reuptake": 0.5,
      "diffusion": 0.02,
      "used": true
    },
    {
      "name": "gaba",
      "base": 0.1,
      "release": 0.1,
      "reuptake": 0.9,
      "diffusion": 0.01,
      "used": true
    }
  ],
  "param_scopes": [
    {
      "name": "trunk",
      "populations": [
        "sensory",
        "association",
        "thalamus",
        "world",
        "self_m",
        "qualia",
        "gws",
        "neural_geometry",
        "entorhinal",
        "pfc",
        "acc",
        "forward_m",
        "evaluator",
        "dmn",
        "thought_transformer",
        "claustrum",
        "motor",
        "reasoning_cortex"
      ],
      "gradient": "normal"
    },
    {
      "name": "bio",
      "populations": [
        "amygdala",
        "insula",
        "hippo",
        "cerebellum",
        "bg",
        "vta",
        "nucleus_accumbens",
        "locus_coeruleus",
        "raphe_nuclei",
        "nucleus_basalis",
        "substantia_nigra"
      ],
      "gradient": "detached_from_main_loss"
    }
  ],
  "formal_specs": [
    {
      "name": "formal_phi_integration",
      "spec_type": "integrated_information",
      "properties": {
        "rule": "\"integrated_information\"",
        "metric": "\"phi\"",
        "# Measure 1": "Non-zero gradient paths (each path = a degree of freedom)",
        "causal_density": "{\n        formula: \"paths_active = count(|\u2207 synaptic_weight| > \u03b5)\",\n        target: \"paths_active > 80% of total synapses\"  # most pathways active"
      }
    },
    {
      "name": "formal_bowtie_topology",
      "spec_type": "narrowing_widening",
      "properties": {
        "rule": "\"narrowing_widening\"",
        "metric": "\"structural_constraint\"",
        "# Requirement 1": "Narrowing phase (all sensory \u2192 bowtie input)",
        "narrowing_phase": "{\n        bowtie_inputs: [\"thalamus\", \"association\"],\n        constraint: \"All sensory synapses must target one of bowtie_inputs\",\n        verification: \"linter checks: sensory -> (thalamus | association) only\""
      }
    }
  ],
  "sheaves": [
    {
      "name": "sheaf_narrative_consistency",
      "contradiction_threshold": 0.7,
      "mechanism": "h1_cohomology_proxy",
      "action": "supersedes"
    }
  ]
}
