"""Extract @export directives from .neuro architecture files.

Convention: place ``# @export KEY = expression`` comments in arch.neuro.
The expression is either:
  - A dot-path into a parsed expert block: ``GeneralExpert.model``
  - A quoted string literal:               ``"~147M"``
  - A bare word (returned as-is):           ``somevalue``

Usage:
    from neuroslm.arch_exports import collect_arch_exports, write_neuro_exports

    exports = collect_arch_exports(Path("architectures/master/arch.neuro"))
    write_neuro_exports(exports, Path(".neuro"))
"""
from __future__ import annotations

import re
from pathlib import Path

# ── regex patterns ────────────────────────────────────────────────────

# expert Name { ... }  (capture name + body)
_EXPERT_BLOCK_RE = re.compile(
    r'\bexpert\s+(\w+)\s*\{([^}]*)\}',
    re.DOTALL,
)

# key: "value"  or  key: value  inside an expert block
_FIELD_RE = re.compile(
    r'\b(\w+)\s*:\s*"([^"]*)"'          # key: "quoted"
    r'|'
    r'\b(\w+)\s*:\s*([^",\n}]+)',        # key: unquoted
)

# # @export KEY = expression   (comment-based, so DSL parser ignores them)
_EXPORT_RE = re.compile(
    r'^\s*#\s*@export\s+([A-Z][A-Z0-9_]*)\s*=\s*(.+)$',
    re.MULTILINE,
)


# ── public API ────────────────────────────────────────────────────────

def parse_expert_blocks(text: str) -> dict[str, dict[str, str]]:
    """Return ``{ExpertName: {field: value}}`` for every ``expert Name { ... }`` block."""
    result: dict[str, dict[str, str]] = {}
    for m in _EXPERT_BLOCK_RE.finditer(text):
        name = m.group(1)
        body = m.group(2)
        fields: dict[str, str] = {}
        for fm in _FIELD_RE.finditer(body):
            if fm.group(1) is not None:
                # quoted form
                fields[fm.group(1)] = fm.group(2).strip()
            else:
                # unquoted form
                key = fm.group(3)
                val = fm.group(4).strip().rstrip(',')
                fields[key] = val
        result[name] = fields
    return result


def parse_export_directives(text: str) -> list[tuple[str, str]]:
    """Return ``[(KEY, expression_string), ...]`` for every ``# @export`` comment."""
    return [
        (m.group(1), m.group(2).strip())
        for m in _EXPORT_RE.finditer(text)
    ]


def resolve_export_expr(expr: str, experts: dict[str, dict[str, str]]) -> str:
    """Evaluate *expr* against *experts* and return a string value.

    - ``Name.field``  → look up in experts dict
    - ``"quoted"``    → strip quotes
    - ``'quoted'``    → strip quotes
    - bare word       → return as-is
    - unresolvable    → return ``""``
    """
    expr = expr.strip()

    # Quoted string literal
    if (expr.startswith('"') and expr.endswith('"')) or \
       (expr.startswith("'") and expr.endswith("'")):
        return expr[1:-1]

    # Dot-path: ExpertName.field
    if '.' in expr:
        obj, _, field = expr.partition('.')
        obj = obj.strip()
        field = field.strip()
        if obj in experts and field in experts[obj]:
            return experts[obj][field]
        return ""

    # Bare word
    return expr


def collect_arch_exports(arch_neuro_path: Path) -> dict[str, str]:
    """Parse *arch_neuro_path* and return all ``# @export`` values as a flat dict.

    Unresolvable expressions (unknown expert / missing field) are silently
    omitted from the result. Empty-string values are also omitted.

    Raises :class:`FileNotFoundError` if the file does not exist.
    """
    if not arch_neuro_path.exists():
        raise FileNotFoundError(f"arch.neuro not found: {arch_neuro_path}")

    text = arch_neuro_path.read_text(encoding="utf-8")
    experts = parse_expert_blocks(text)
    directives = parse_export_directives(text)

    exports: dict[str, str] = {}
    for key, expr in directives:
        value = resolve_export_expr(expr, experts)
        if value:  # skip empty/unresolvable
            exports[key] = value
    return exports


def write_neuro_exports(exports: dict[str, str], neuro_dir: Path) -> Path:
    """Write *exports* as TOML to ``<neuro_dir>/exports.toml``.

    Creates *neuro_dir* if it does not exist. Overwrites any existing file.
    Returns the path written.
    """
    neuro_dir.mkdir(parents=True, exist_ok=True)
    out = neuro_dir / "exports.toml"

    lines = [
        "# Auto-generated by brian update-readme — do not edit by hand.\n",
        "# Source: arch.neuro # @export directives\n",
        "\n",
        "[exports]\n",
    ]
    for key in sorted(exports):
        value = exports[key].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{key} = "{value}"\n')

    out.write_text("".join(lines), encoding="utf-8")
    return out
