# -*- coding: utf-8 -*-
"""Vast.ai connector for an ISAAC SIM SENSORY-SOURCE box
(``brian deploy-isaac-sim``) — §15's remote bridge, deployed.

Sibling of :mod:`vast_mind`, not a modification of it: an Isaac Sim
box has a genuinely different shape (a different pip package entirely,
a different GPU class, no ``neuroslm`` model to load) — same reasoning
``vast_discover.sh``'s own docstring gives for not bolting a second
job type onto the well-tested training launcher.

**Why a separate box from the mind.** Isaac Sim's renderer needs an
RTX-class GPU (hardware ray-tracing cores); this project's mind boxes
default to A100 (no RT cores). Two boxes, two GPUs, connected over the
network — see :func:`neuroslm.cognition.server.open_isaac_relay` for
how a laptop-owned SSH tunnel pair connects them without either rented
box ever holding the operator's private key.

**Why pip, not the NGC Docker container.** NVIDIA also ships Isaac Sim
as ``nvcr.io/nvidia/isaac-sim``, but pulling it needs an NGC account +
API key and (on vast.ai) either a registry-auth-capable image slot or
docker-in-docker — both add real risk this connector can't verify
without live hardware. The pip distribution
(``pip install isaacsim[all,extscache]==<version> --extra-index-url
https://pypi.nvidia.com``) needs no registry auth at all and fits the
SAME stock-CUDA-image + onstart-script pattern every other connector
in this repo already uses (reuses ``scripts/vast_discover.sh``
verbatim, exactly like :mod:`vast_mind` does).

**⚠ UNVERIFIED.** Per CLAUDE.md §1's own exemption, vast.ai deploy
scripts are "verified by deploying, not unit-tested." The Python-side
config/CLI/onstart-templating below IS unit-tested (mirrors
:mod:`vast_mind`'s coverage exactly). The actual Isaac Sim boot
sequence — pip install timing (~10-15 min first run), the exact
current ``isaacsim.core.api``/``isaacsim.sensors.camera`` import
surface, GLIBC/Python-version compatibility on the base image — has
NOT been run against real hardware and WILL need iteration on first
deploy. See docs/findings.md for the explicit list of what to check.

The server binds 127.0.0.1 on the box, same as the mind; nothing is
ever publicly exposed.
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parents[2]

# RTX-class card — A100 (the mind's own default) has no RT cores.
# 24 GiB (4090-class) comfortably clears Isaac Sim's stated 16 GiB
# VRAM floor. Override via --gpu-query for a different card class.
_DEFAULT_GPU_QUERY = ("gpu_name=RTX_4090 num_gpus=1 rentable=true "
                      "verified=true reliability>0.95")


@dataclass
class IsaacSimDeployConfig:
    isaac_sim_version: str = "4.5.0"
    branch: Optional[str] = None
    label: str = "neuroslm-isaac"
    gpu_query: str = _DEFAULT_GPU_QUERY
    # The mind-server port the sensor loop will reach at
    # 127.0.0.1:port on ITS OWN box — via open_isaac_relay's reverse
    # tunnel, not a direct connection to the mind box.
    port: int = 7861
    camera_prim_path: str = "/World/Camera"


# The standalone Isaac Sim script, written to the box and run under
# its own pip-installed Python environment. SimulationApp() must be
# constructed before any isaacsim/omni import — Isaac Sim's own
# documented standalone-script contract.
_SENSOR_LOOP_SCRIPT = '''\
# -*- coding: utf-8 -*-
"""Isaac Sim standalone sensor loop (generated by
neuroslm.connectors.vast_isaac). UNVERIFIED against real hardware —
see docs/findings.md before debugging a failed boot."""
import sys
import time

sys.path.insert(0, "/workspace/brian")

from isaacsim import SimulationApp
simulation_app = SimulationApp({"headless": True})

# isaacsim/omni imports are only valid AFTER SimulationApp() exists.
from isaacsim.core.api import World

from neuroslm.connectors.isaac_sim import OmniverseIsaacSimClient, SensoryBridge
from neuroslm.cognition.server import RemoteMindProxy

world = World()
world.scene.add_default_ground_plane()
world.reset()

print("[isaac_sensor_loop] connecting to the mind via the operator's "
     "relay tunnel (127.0.0.1:__PORT__) ...", flush=True)
proxy = RemoteMindProxy(host="127.0.0.1", port=__PORT__)
client = OmniverseIsaacSimClient(camera_prim_path="__CAMERA_PRIM_PATH__")
bridge = SensoryBridge(proxy, client)

print("[isaac_sensor_loop] booted -- pumping sensory input to the mind",
     flush=True)
while simulation_app.is_running():
    world.step(render=True)
    attended = bridge.pump()
    if attended:
        print(f"[isaac_sensor_loop] {attended}", flush=True)
    time.sleep(0.1)
'''

_ONSTART_TEMPLATE = """\
set -e
export DEBIAN_FRONTEND=noninteractive
date -u +"vast_isaac boot @ %Y-%m-%dT%H:%M:%SZ"

(command -v git >/dev/null 2>&1 && command -v git-lfs >/dev/null 2>&1) \\
    || (apt-get update -y && apt-get install -y git git-lfs)
git lfs install --skip-smudge

export GH_TOKEN='__GH_TOKEN__' HF_TOKEN='__HF_TOKEN__'
mkdir -p /workspace && cd /workspace

echo "── cloning __BRANCH__ ──"
GIT_LFS_SKIP_SMUDGE=1 git clone --branch '__BRANCH__' --single-branch \\
    "https://x-access-token:${GH_TOKEN}@github.com/__REPO_SLUG__.git" brian
cd /workspace/brian

echo "── Isaac Sim's own Python environment (isaacsim pins its Python "
echo "   version -- do NOT reuse the repo's .venv convention here, this"
echo "   is disposable rented infra, not local dev) ──"
PYBIN="$(command -v python3.10 || command -v python3)"
"$PYBIN" -m venv /workspace/isaac_venv
/workspace/isaac_venv/bin/pip install --upgrade pip
echo "── installing isaacsim __ISAAC_SIM_VERSION__ (first run: 10-15 "
echo "   min extension cache download, no progress bar) ──"
/workspace/isaac_venv/bin/pip install \\
    "isaacsim[all,extscache]==__ISAAC_SIM_VERSION__" \\
    --extra-index-url https://pypi.nvidia.com

echo "── installing neuroslm (cortices + sensory bridge + RemoteMindProxy) ──"
/workspace/isaac_venv/bin/pip install -e /workspace/brian[ml]

cat > /workspace/isaac_sensor_loop.py <<'PYEOF'
__SENSOR_LOOP_SCRIPT__
PYEOF

mkdir -p logs/isaac
export ACCEPT_EULA=Y PRIVACY_CONSENT=Y OMNI_KIT_ACCEPT_EULA=YES
echo "── starting the isaac sim sensor loop (crash-restart loop) ──"
# NO self-destroy: an isaac-sim sensory source is an always-on
# companion to the mind box, same philosophy as vast_mind.py — bills
# until `brian destroy <id>`. 10s backoff so a hard boot failure
# can't hot-spin the billing meter against a broken install.
while true; do
    date -u +"[isaac-loop] (re)start @ %Y-%m-%dT%H:%M:%SZ"
    # omni.kit_app's check_eula() calls input() at import time — a
    # bare stdin read, not an env-var check (ACCEPT_EULA alone does
    # NOT satisfy it). In this non-interactive onstart context stdin
    # would otherwise EOF immediately and the loop would hammer the
    # same prompt every 10s forever without ever reaching the sensor
    # loop (live incident, 2026-08-12) — `yes 'Yes'` feeds it an
    # answer on every input() call for as long as the process runs.
    # Fed via process substitution (not a literal pipe stage) so the
    # main pipeline stays python|tee and PIPESTATUS[0] below is still
    # python's own exit code.
    /workspace/isaac_venv/bin/python /workspace/isaac_sensor_loop.py \\
        < <(yes 'Yes') 2>&1 | tee -a "logs/isaac/$(date -u +%Y%m%d)_isaac.log"
    # `${PIPESTATUS[0]}` is the PYTHON process's exit code — a bare
    # `$?` here would report the LAST pipeline stage (tee, always 0),
    # masking every real crash as "rc=0" (live incident, same boot).
    echo "[isaac-loop] process exited rc=${PIPESTATUS[0]} — restarting in 10s"
    sleep 10
done
"""


def build_isaac_onstart(env: dict) -> str:
    """Container-side onstart script. Same locally-expanded-placeholder
    pattern as :func:`vast_mind.build_mind_onstart`."""
    sensor_loop = (_SENSOR_LOOP_SCRIPT
                   .replace("__PORT__", str(env.get("PORT", 7861)))
                   .replace("__CAMERA_PRIM_PATH__",
                           str(env.get("CAMERA_PRIM_PATH", "/World/Camera"))))

    result = _ONSTART_TEMPLATE
    repo_slug = env.get("REPO_URL") or "269652/BRIAN"
    repo_slug = (repo_slug.replace("https://github.com/", "")
                 .replace(".git", ""))
    replacements = {
        "__GH_TOKEN__": str(env.get("GH_TOKEN", "")),
        "__HF_TOKEN__": str(env.get("HF_TOKEN", "")),
        "__BRANCH__": str(env.get("BRANCH", "master")),
        "__REPO_SLUG__": repo_slug,
        "__ISAAC_SIM_VERSION__": str(env.get("ISAAC_SIM_VERSION", "4.5.0")),
        "__SENSOR_LOOP_SCRIPT__": sensor_loop,
    }
    for key, val in replacements.items():
        result = result.replace(key, val)
    return result


class VastIsaacConnector:
    """Launch an Isaac Sim sensory-source box via
    ``scripts/vast_discover.sh`` — same reuse :mod:`vast_mind` makes."""

    @staticmethod
    def _find_bash() -> str:
        from neuroslm.connectors.vast import VastConnector
        return VastConnector._find_bash()

    def launch(self, config: IsaacSimDeployConfig) -> int:
        from neuroslm.connectors.vast_discover import _current_branch

        # ── §8.1: walk .env into os.environ BEFORE reading tokens ──
        # Same fix vast_mind.py needed for the same reason.
        try:
            from neuroslm.utils.secrets import bootstrap_secrets
            bootstrap_secrets(
                ["GH_TOKEN", "HF_TOKEN", "VAST_API_KEY"],
                aliases={"GH_TOKEN": ("GITHUB_TOKEN", "GITHUB_PAT")},
                verbose=False)
        except Exception as exc:
            print(f"[deploy-isaac-sim] (note) secrets bootstrap skipped: "
                  f"{type(exc).__name__}: {exc}", file=sys.stderr)

        if not os.environ.get("GH_TOKEN"):
            print("[deploy-isaac-sim] ⚠ GH_TOKEN missing (checked process "
                  "env and .env) — the box will fail to clone the repo. "
                  "Set it before deploying: export GH_TOKEN=ghp_... or "
                  "add it to .env.", file=sys.stderr)

        branch = config.branch or _current_branch()
        onstart_content = build_isaac_onstart({
            "GH_TOKEN": os.environ.get("GH_TOKEN", ""),
            "HF_TOKEN": os.environ.get("HF_TOKEN", ""),
            "BRANCH": branch,
            "REPO_URL": os.environ.get("REPO_URL", ""),
            "ISAAC_SIM_VERSION": config.isaac_sim_version,
            "PORT": config.port,
            "CAMERA_PRIM_PATH": config.camera_prim_path,
        })

        tf = tempfile.NamedTemporaryFile(
            mode="w", suffix=".sh", delete=False, encoding="utf-8",
            newline="\n")
        try:
            tf.write(onstart_content)
            tf.flush()
            tf.close()

            env = os.environ.copy()
            env["ONSTART_FILE"] = tf.name
            env["VAST_LABEL"] = config.label
            env["GPU_QUERY"] = config.gpu_query

            bash = self._find_bash()
            script = str(REPO_ROOT / "scripts" / "vast_discover.sh")
            print(f"$ {bash} {script}")
            return subprocess.call(
                [bash, script],
                cwd=str(REPO_ROOT),
                env=env,
                stdin=subprocess.DEVNULL,
            )
        finally:
            try:
                os.unlink(tf.name)
            except OSError:
                pass
