# -*- coding: utf-8 -*-
"""Vast.ai connector for an ISAAC SIM SENSORY-SOURCE box
(``brian deploy-isaac-sim``) — §15's remote bridge, deployed.

Sibling of :mod:`vast_mind`, not a modification of it: an Isaac Sim
box has a genuinely different shape (a different container image
entirely, private-registry auth, a different GPU class, no
``neuroslm`` model to load) — same reasoning ``vast_discover.sh``'s
own docstring gives for not bolting a second job type onto the
well-tested training launcher.

**Why a separate box from the mind.** Isaac Sim's renderer needs an
RTX-class GPU (hardware ray-tracing cores); this project's mind boxes
default to A100 (no RT cores). Two boxes, two GPUs, connected over the
network — see :func:`neuroslm.cognition.server.open_isaac_relay` for
how a laptop-owned SSH tunnel pair connects them without either rented
box ever holding the operator's private key.

**Why the NGC Docker container, not pip.** The pip distribution
(``pip install isaacsim[all,extscache]``) was tried first and hit a
fatal wall LIVE (2026-08-12): ``SimulationApp``'s OWN constructor
raised ``ImportError: libomni.usd.so: cannot open shared object
file`` — a missing native library in the pip package's dependency
resolution on a stock CUDA image, not a bug in this connector's code.
The NGC container (``nvcr.io/nvidia/isaac-sim``) is NVIDIA's
fully-tested, self-contained artifact — it doesn't have this class of
problem because every native lib it needs ships pre-linked inside the
image. Pulling a private NGC image from vast.ai needs the account's
own NGC API key; ``vastai create instance`` has a documented
``--login`` flag for exactly this (verified via ``vastai create
instance --help``, not guessed — see the worked example in that
command's own docstring: ``--login '-u bob -p PASS docker.io'``).
``scripts/vast_discover.sh`` was extended (additively — existing
public-image callers are unaffected) with ``VAST_IMAGE``/``VAST_LOGIN``
env-var overrides for exactly this.

**⚠ UNVERIFIED.** Per CLAUDE.md §1's own exemption, vast.ai deploy
scripts are "verified by deploying, not unit-tested." The Python-side
config/CLI/onstart-templating below IS unit-tested (mirrors
:mod:`vast_mind`'s coverage exactly). NOT verified: whether vast.ai's
own infrastructure actually honours ``--login`` for every host in the
offer pool, whether the container's bundled ``isaacsim`` Python API
surface matches what :mod:`neuroslm.connectors.isaac_sim` expects, and
image-pull timing for a multi-GB NGC image. See docs/findings.md for
the explicit list of what to check on first deploy.

The server binds 127.0.0.1 on the box, same as the mind; nothing is
ever publicly exposed.
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parents[2]

# RTX-class card — A100 (the mind's own default) has no RT cores.
# 24 GiB (4090-class) comfortably clears Isaac Sim's stated 16 GiB
# VRAM floor. Override via --gpu-query for a different card class.
_DEFAULT_GPU_QUERY = ("gpu_name=RTX_4090 num_gpus=1 rentable=true "
                      "verified=true reliability>0.95")

_NGC_IMAGE = "nvcr.io/nvidia/isaac-sim"


@dataclass
class IsaacSimDeployConfig:
    image_tag: str = "6.0.1"
    branch: Optional[str] = None
    label: str = "neuroslm-isaac"
    gpu_query: str = _DEFAULT_GPU_QUERY
    # The mind-server port the sensor loop will reach at
    # 127.0.0.1:port on ITS OWN box — via open_isaac_relay's reverse
    # tunnel, not a direct connection to the mind box.
    port: int = 7861
    camera_prim_path: str = "/World/Camera"


# The standalone Isaac Sim script, written to the box and run under
# the CONTAINER's own bundled Python (/isaac-sim/python.sh) — no
# separate pip-managed venv; the NGC image already IS a complete,
# pre-linked Isaac Sim environment. SimulationApp() must be
# constructed before any isaacsim/omni import — Isaac Sim's own
# documented standalone-script contract, unchanged by install method.
_SENSOR_LOOP_SCRIPT = '''\
# -*- coding: utf-8 -*-
"""Isaac Sim standalone sensor loop (generated by
neuroslm.connectors.vast_isaac). UNVERIFIED against real hardware —
see docs/findings.md before debugging a failed boot."""
import sys
import time

sys.path.insert(0, "/workspace/brian")

from isaacsim import SimulationApp
# Live incident (2026-08-24): headless=True alone boots the Kit
# framework fine but never turns on the RTX render pipeline cameras
# need -- get_rgba() returned None forever, confirmed live (the box
# ran crash-free for 10+ minutes with zero frames ever reaching the
# mind). enable_cameras=True is the documented fix for exactly this.
simulation_app = SimulationApp({"headless": True, "enable_cameras": True})

# isaacsim/omni imports are only valid AFTER SimulationApp() exists.
from isaacsim.core.api import World

from neuroslm.connectors.isaac_sim import OmniverseIsaacSimClient, SensoryBridge
from neuroslm.cognition.server import RemoteMindProxy

world = World()
world.scene.add_default_ground_plane()
world.reset()

print("[isaac_sensor_loop] connecting to the mind via the operator's "
     "relay tunnel (127.0.0.1:__PORT__) ...", flush=True)
proxy = RemoteMindProxy(host="127.0.0.1", port=__PORT__)
client = OmniverseIsaacSimClient(camera_prim_path="__CAMERA_PRIM_PATH__")
bridge = SensoryBridge(proxy, client)

print("[isaac_sensor_loop] booted -- pumping sensory input to the mind",
     flush=True)
while simulation_app.is_running():
    world.step(render=True)
    attended = bridge.pump()
    if attended:
        print(f"[isaac_sensor_loop] {attended}", flush=True)
    time.sleep(0.1)
'''

_ONSTART_TEMPLATE = """\
set -e
export DEBIAN_FRONTEND=noninteractive
date -u +"vast_isaac boot @ %Y-%m-%dT%H:%M:%SZ"

__SSH_KEY_INJECTION__
(command -v git >/dev/null 2>&1 && command -v git-lfs >/dev/null 2>&1) \\
    || (apt-get update -y && apt-get install -y git git-lfs)
git lfs install --skip-smudge

export GH_TOKEN='__GH_TOKEN__' HF_TOKEN='__HF_TOKEN__'
mkdir -p /workspace && cd /workspace

echo "── cloning __BRANCH__ ──"
GIT_LFS_SKIP_SMUDGE=1 git clone --branch '__BRANCH__' --single-branch \\
    "https://x-access-token:${GH_TOKEN}@github.com/__REPO_SLUG__.git" brian
cd /workspace/brian

echo "── installing neuroslm (cortices + sensory bridge + RemoteMindProxy) "
echo "   into the CONTAINER's own Isaac Sim Python — no separate venv, "
echo "   the NGC image already IS the environment ──"
/isaac-sim/python.sh -m pip install -e /workspace/brian[ml]

cat > /workspace/isaac_sensor_loop.py <<'PYEOF'
__SENSOR_LOOP_SCRIPT__
PYEOF

mkdir -p logs/isaac
# The container's own documented headless-EULA mechanism.
export ACCEPT_EULA=Y PRIVACY_CONSENT=Y OMNI_KIT_ACCEPT_EULA=YES
echo "── starting the isaac sim sensor loop (crash-restart loop) ──"
# NO self-destroy: an isaac-sim sensory source is an always-on
# companion to the mind box, same philosophy as vast_mind.py — bills
# until `brian destroy <id>`. 10s backoff so a hard boot failure
# can't hot-spin the billing meter against a broken install.
while true; do
    date -u +"[isaac-loop] (re)start @ %Y-%m-%dT%H:%M:%SZ"
    # omni.kit_app's check_eula() calls input() at import time — a
    # bare stdin read, not (necessarily) satisfied by the env vars
    # above alone. Defensive even on the container image: harmless if
    # unneeded (`yes` just runs until the pipe closes). Fed via
    # process substitution (not a literal pipe stage) so the main
    # pipeline stays python|tee and PIPESTATUS[0] below is still
    # python's own exit code.
    /isaac-sim/python.sh /workspace/isaac_sensor_loop.py \\
        < <(yes 'Yes') 2>&1 | tee -a "logs/isaac/$(date -u +%Y%m%d)_isaac.log"
    # `${PIPESTATUS[0]}` is the PYTHON process's exit code — a bare
    # `$?` here would report the LAST pipeline stage (tee, always 0),
    # masking every real crash as "rc=0" (live incident, 2026-08-12).
    echo "[isaac-loop] process exited rc=${PIPESTATUS[0]} — restarting in 10s"
    sleep 10
done
"""


def _build_ssh_key_injection_block(public_keys: str) -> str:
    """Live incident (2026-08-24): the NGC container image doesn't get
    vast.ai's standard per-account SSH key auto-injection the way the
    mind box's stock pytorch/pytorch image does — `vastai attach ssh`
    even reported the key as 'already associated' with the instance
    while it kept denying publickey auth, and rebooting didn't fix it
    either. Rather than depend on a propagation mechanism this custom
    image evidently doesn't honour, write the key(s) into
    authorized_keys ourselves, unconditionally, as the very first
    thing the onstart does — public keys are not secrets, safe to
    embed literally. Empty input means no block at all (clean no-op,
    not an empty heredoc).

    Take two, same day: the chmod-only version above still got
    sshd's `Authentication refused: bad ownership or modes for file
    /root/.ssh/authorized_keys` — `mkdir -p` is a no-op on a
    pre-existing `.ssh` dir (plausibly left by a partial vast.ai
    injection attempt with the wrong owner), so `chmod` alone never
    touched OWNERSHIP; sshd's StrictModes rejects on either mismatch.
    `chown` explicitly, and use the absolute `/root/.ssh` path — this
    always runs as root (the apt-get calls elsewhere in the onstart
    already require it), so there's no ambiguity to remove by using
    `~`, only a reason not to trust it."""
    keys = [k for k in public_keys.splitlines() if k.strip()]
    if not keys:
        return ""
    key_block = "\n".join(keys)
    return (
        # StrictModes walks the WHOLE ancestor chain, not just .ssh —
        # a group/world-writable /root trips the same rejection
        # regardless of .ssh's own perms. go-w only strips write bits
        # (doesn't touch read/execute), the minimal change that
        # satisfies sshd without guessing at a specific numeric mode
        # some other process in the image might depend on.
        "chmod go-w /root\n"
        "mkdir -p /root/.ssh\n"
        "chown root:root /root/.ssh\n"
        "chmod 700 /root/.ssh\n"
        "cat >> /root/.ssh/authorized_keys <<'KEYEOF'\n"
        f"{key_block}\n"
        "KEYEOF\n"
        "chown root:root /root/.ssh/authorized_keys\n"
        "chmod 600 /root/.ssh/authorized_keys\n"
        f'echo "── injected {len(keys)} account SSH public key(s) — this '
        "custom image doesn't reliably get vast.ai's own per-instance "
        'key auto-injection ──"\n'
    )


def build_isaac_onstart(env: dict) -> str:
    """Container-side onstart script. Same locally-expanded-placeholder
    pattern as :func:`vast_mind.build_mind_onstart`."""
    sensor_loop = (_SENSOR_LOOP_SCRIPT
                   .replace("__PORT__", str(env.get("PORT", 7861)))
                   .replace("__CAMERA_PRIM_PATH__",
                           str(env.get("CAMERA_PRIM_PATH", "/World/Camera"))))

    result = _ONSTART_TEMPLATE
    repo_slug = env.get("REPO_URL") or "269652/BRIAN"
    repo_slug = (repo_slug.replace("https://github.com/", "")
                 .replace(".git", ""))
    replacements = {
        "__GH_TOKEN__": str(env.get("GH_TOKEN", "")),
        "__HF_TOKEN__": str(env.get("HF_TOKEN", "")),
        "__BRANCH__": str(env.get("BRANCH", "master")),
        "__REPO_SLUG__": repo_slug,
        "__SENSOR_LOOP_SCRIPT__": sensor_loop,
        "__SSH_KEY_INJECTION__": _build_ssh_key_injection_block(
            str(env.get("SSH_PUBLIC_KEYS", ""))),
    }
    for key, val in replacements.items():
        result = result.replace(key, val)
    return result


class VastIsaacConnector:
    """Launch an Isaac Sim sensory-source box via
    ``scripts/vast_discover.sh`` — same reuse :mod:`vast_mind` makes,
    now with the ``VAST_IMAGE``/``VAST_LOGIN`` overrides that script
    gained for exactly this connector."""

    @staticmethod
    def _find_bash() -> str:
        from neuroslm.connectors.vast import VastConnector
        return VastConnector._find_bash()

    @staticmethod
    def _fetch_ssh_public_keys() -> list:
        """The account's registered SSH public keys, via ``vastai show
        ssh-keys --raw`` — public keys, not secrets. Injected directly
        into the isaac box's onstart because vast.ai's own per-instance
        injection doesn't reliably reach this custom image (live
        incident, 2026-08-24)."""
        import json
        out = subprocess.run(["vastai", "show", "ssh-keys", "--raw"],
                             capture_output=True, text=True, timeout=20)
        if out.returncode != 0:
            raise RuntimeError(f"vastai show ssh-keys failed: {out.stderr.strip()}")
        rows = json.loads(out.stdout)
        return [r["public_key"] for r in rows if r.get("public_key")]

    def launch(self, config: IsaacSimDeployConfig) -> int:
        from neuroslm.connectors.vast_discover import _current_branch

        # ── §8.1: walk .env into os.environ BEFORE reading tokens ──
        # Same fix vast_mind.py needed for the same reason.
        try:
            from neuroslm.utils.secrets import bootstrap_secrets
            bootstrap_secrets(
                ["GH_TOKEN", "HF_TOKEN", "VAST_API_KEY", "NGC_API_KEY"],
                aliases={"GH_TOKEN": ("GITHUB_TOKEN", "GITHUB_PAT")},
                verbose=False)
        except Exception as exc:
            print(f"[deploy-isaac-sim] (note) secrets bootstrap skipped: "
                  f"{type(exc).__name__}: {exc}", file=sys.stderr)

        if not os.environ.get("GH_TOKEN"):
            print("[deploy-isaac-sim] ⚠ GH_TOKEN missing (checked process "
                  "env and .env) — the box will fail to clone the repo. "
                  "Set it before deploying: export GH_TOKEN=ghp_... or "
                  "add it to .env.", file=sys.stderr)
        ngc_api_key = os.environ.get("NGC_API_KEY", "")
        if not ngc_api_key:
            print("[deploy-isaac-sim] ⚠ NGC_API_KEY missing (checked "
                  "process env and .env) — the private nvcr.io pull will "
                  "fail. Get one at ngc.nvidia.com → Setup → Get API Key, "
                  "then export NGC_API_KEY=... or add it to .env.",
                  file=sys.stderr)

        # §8.1 "fail open": a fetch failure must not crash the deploy
        # chain — the box just boots without the defensive key
        # injection (same as before this fix existed), not silently
        # (a warning is printed either way).
        try:
            ssh_keys = self._fetch_ssh_public_keys()
            if not ssh_keys:
                print("[deploy-isaac-sim] (note) no SSH public keys "
                      "registered on the account — skipping the "
                      "defensive authorized_keys injection.",
                      file=sys.stderr)
        except Exception as exc:
            print(f"[deploy-isaac-sim] ⚠ could not fetch SSH public keys "
                  f"({type(exc).__name__}: {exc}) — the box will rely on "
                  "vast.ai's own key injection alone, which has been "
                  "unreliable for this custom image.", file=sys.stderr)
            ssh_keys = []

        branch = config.branch or _current_branch()
        onstart_content = build_isaac_onstart({
            "GH_TOKEN": os.environ.get("GH_TOKEN", ""),
            "HF_TOKEN": os.environ.get("HF_TOKEN", ""),
            "BRANCH": branch,
            "REPO_URL": os.environ.get("REPO_URL", ""),
            "PORT": config.port,
            "CAMERA_PRIM_PATH": config.camera_prim_path,
            "SSH_PUBLIC_KEYS": "\n".join(ssh_keys),
        })

        tf = tempfile.NamedTemporaryFile(
            mode="w", suffix=".sh", delete=False, encoding="utf-8",
            newline="\n")
        try:
            tf.write(onstart_content)
            tf.flush()
            tf.close()

            env = os.environ.copy()
            env["ONSTART_FILE"] = tf.name
            env["VAST_LABEL"] = config.label
            env["GPU_QUERY"] = config.gpu_query
            env["VAST_IMAGE"] = f"{_NGC_IMAGE}:{config.image_tag}"
            # NGC's API-key auth ALWAYS uses the literal username
            # $oauthtoken (not a real account name) — never baked into
            # the container's own --env (it authenticates the PULL
            # only, the running container never needs it).
            env["VAST_LOGIN"] = f"-u $oauthtoken -p {ngc_api_key} nvcr.io"

            bash = self._find_bash()
            script = str(REPO_ROOT / "scripts" / "vast_discover.sh")
            print(f"$ {bash} {script}")
            return subprocess.call(
                [bash, script],
                cwd=str(REPO_ROOT),
                env=env,
                stdin=subprocess.DEVNULL,
            )
        finally:
            try:
                os.unlink(tf.name)
            except OSError:
                pass
